var KEY1 = 350;
var KEY2 = 351;
var FORM_TYPE = 352;
var HEADER = 353;
var FTR_NAME2 = 354;
var MEMO = 355;
var OKSEQNO = 356;
var OD_PRICE2 = 357;
var OD_QTY2 = 358;
var BFR_QTY = 359;
var AFT_QTY = 360;
var FUNCTIONCODE = 361;
var SRC_CODE = 362;
var ORG_QTY2 = 363;
var DEAL_QTY = 364;
var DEAL_QTY2 = 365;
var DEAL_AVGPRICE = 366;
var TRANS_DATE = 159;
var MATCH_TIME = 310;
//'var  BRANCH_ID = 1;
var ORDNO = 147;
var S_OD_SEQ = 143;
var F_OD_SEQ = 208;
//'var  CUST_ID = 39;
var STK_ID = 85;
var FTR_ID = 114;
var FTR_MTH = 115;
var CALLPUT = 116;
var STRIKE_PRICE = 117;
var BUYSELL = 148;
var FTR_ID2 = 130;
var FTR_MTH2 = 131;
var CALLPUT2 = 132;
var STRIKE_PRICE2 = 133;
var BUYSELL2 = 134;
var PRICE_FLAG = 150;
var OPENCLOSE = 163;
var OD_TYPE = 149;
//'var  AGENT_ID = 5;
var ERR_CODE = 68;
var ERR_MSG = 69;
var OD_PRICE = 151;
var OBOD_PRICE = 257;
var OD_QTY = 156;
var OD_KEY = 201;
var F_ORG_SEQ = 204;
var S_ORG_SEQ = 144;
var MARKET_TYPE = 101;
var TRADE_TYPE = 153;
var STOP_PRICE = 219;
var ORDER_KEY = 201;
var EXCHANGE = 218;
var DAY_TRADE = 220;
                       
        
//艾揚下單使用                 '  證券                    期貨         選擇權             複式
var ORDER_ARGS_ROCID = 0;            //'X 身份證字號(登入帳號)           *             *               *
var ORDER_ARGS_PASSWORD = 1;    //     'X 登入密碼                       *             *               *
var ORDER_ARGS_BRANCHID = 2;        // 'X 分公司代號                     *             *               *
var ORDER_ARGS_CUSTID = 3;           //X 帳號                           *             *               *
var ORDER_ARGS_AGENTID = 4;          //X 營業員代碼                     *             *               *
var ORDER_ARGS_SOURCE = 5;        //   'X 來源別                         *             *               *
var ORDER_ARGS_ID = 6;               //'X 商品代碼                       *             *           (第一腳)代碼
var ORDER_ARGS_BS = 7;               //'X 買賣別                         *             *           (第一腳)買賣別
var ORDER_ARGS_ODTYPE = 8;        //   'X 現股(0)/融資(1)/融券(2)        ""      IOC(I)/ROD(R)/FOK(F)    *
var ORDER_ARGS_TRADE_TYPE = 9;  //     'X 普通(N)/盤後(F)/零股(O)        ""            *               *
var ORDER_ARGS_PRICE_FLAG = 10;   //   'X 市價(1), 限價(0)               *             *               *
var ORDER_ARGS_ODPRICE = 11;         //'9 價格                           *             *               *
var ORDER_ARGS_ODQTY = 12;           //'9 數量                           *             *               *
var ORDER_ARGS_ODKEY = 13;           //'X Order Key                      *             *               *
var ORDER_ARGS_OPENCLOSE = 14;    //   'X -                          新倉(O)/平倉(C)   *               *
var ORDER_ARGS_MTH = 15;             //'X -                              -       (第一腳)履約年月      *
var ORDER_ARGS_CP = 16;              //'X -                              -       (第一腳)Call(C)/Put(P)  *
var ORDER_ARGS_STRIKE = 17;        //  '9 -                              -       (第一腳)履約價          *
var ORDER_ARGS_ID2 = 18;             //'X -                              -             -           (第二腳)代碼
var ORDER_ARGS_BS2 = 19;             //'X -                              -             -           (第二腳)買賣別
var ORDER_ARGS_MTH2 = 20;           // 'X -                              -             -           (第二腳)履約年月
var ORDER_ARGS_CP2 = 21;             //'X -                              -             -           (第二腳)CallPut
var ORDER_ARGS_STRIKE2 = 22;        // '9 -                              -             -           (第二腳)履約價
var ORDER_ARGS_MARKETTYPE = 23;  //    '上市(T)/上櫃(O)                  -             -               -
// '-表示不使用 *表示同左用法
var ORDER_ARGS_EXCHANGE = 24;
var ORDER_ARGS_STOPPRICE = 25;
var ORDER_ARGS_DAYTRADE = 26;

//'以下為刪單改量用到的欄位
var ORDER_ARGS_ORGSEQ = 27;     // '原始網路單號
var ORDER_ARGS_ORGSOURCE = 28;   //'原始來源別
var ORDER_ARGS_ORDNO = 29;       //委託書號
var ORDER_ARGS_CANCELQTY = 30;   //'取消股數/口數

var ORDER_ARGS_AFTERQTY = 31;
var ORDER_ARGS_TRANSDATE = 32;    //'交易日
var ORDER_ARGS_MATCHQTY = 33; //'成交口數